---
version: '3'

services:
  zookeeper-1:
    image: 'docker.io/wurstmeister/zookeeper'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - abhishek-local

  zookeeper-2:
    image: 'docker.io/wurstmeister/zookeeper'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181
    networks:
      - abhishek-local

  zookeeper-3:
    image: 'docker.io/wurstmeister/zookeeper'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 42181:2181
    networks:
      - abhishek-local

  kafka-1:
    image: 'docker.io/wurstmeister/kafka'
    hostname: "kafka-1"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

    ports:
      - 9091:9091
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      HOSTNAME_COMMAND: "hostname"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-1:9092,OUTSIDE://localhost:9091
      KAFKA_LISTENERS: INSIDE://kafka-1:9092,OUTSIDE://:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - abhishek-local

  kafka-2:
    image: 'docker.io/wurstmeister/kafka'
    hostname: "kafka-2"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      HOSTNAME_COMMAND: "hostname"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-2:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://kafka-2:9092,OUTSIDE://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - abhishek-local

  kafka-3:
    image: 'docker.io/wurstmeister/kafka'
    hostname: "kafka-3"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      HOSTNAME_COMMAND: "hostname"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-3:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://kafka-3:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - abhishek-local

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - '9000:9000'
    environment:
      KAFKA_BROKERCONNECT: "kafka-1:9092"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - abhishek-local

networks:
  abhishek-local:
    driver: bridge